namespace PythonCore;

public record Symbol(int StartPos, int EndPos);

public sealed record PyFalse(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyNone(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyTrue(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyAnd(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyAs(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyAssert(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyAsync(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyAwait(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBreak(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyClass(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyContinue(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyDef(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyDel(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyElif(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyElse(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyExcept(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyFinally(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyFor(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyFrom(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyGlobal(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyIf(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyImport(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyIn(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyIs(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyLambda(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyNonlocal(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyNot(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyOr(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyPass(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyRaise(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyReturn(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyTry(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyWhile(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyWith(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyYield(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyMatch(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyCase(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyType(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyDefault(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos); // '_'

public sealed record PyPlus(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyMinus(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyMul(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyPower(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyDiv(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyFloorDiv(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyModulo(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyMatrice(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyShiftLeft(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyShiftRight(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBitAnd(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBitOr(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBitXor(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBitInvert(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyColonAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos); // ':='
public sealed record PyLess(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyGreater(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyLessEqual(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyGreaterEqual(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyEqual(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyNotEqual(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyLeftParen(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyLeftBracket(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyLeftCurly(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyRightParen(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyRightBracket(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyRightCurly(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyComma(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyColon(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyDot(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyElipsis(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyArrow(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyPlusAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyMinusAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyMulAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyDivAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyFloorDivAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyModuloAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyMatriceAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBitAndAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBitOrAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyBitXorAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyShiftLeftAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyShiftRightAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyPowerAssign(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PySemiColon(int StartPos, int EndPos, Trivia[] Trivias) : Symbol(StartPos, EndPos);

public sealed record PyName(int StartPos, int EndPos, string Id, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyNumber(int StartPos, int EndPos, string Number, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyString(int StartPos, int EndPos, string Text, Trivia[] Trivias) : Symbol(StartPos, EndPos);

public sealed record PyEOF(int Position, Trivia[] Trivias) : Symbol(Position, Position);
public sealed record PyNewline(int StartPos, int EndPos, char Ch1, char Ch2, Trivia[] Trivias) : Symbol(StartPos, EndPos);
public sealed record PyIndent(Trivia[] Trivias) : Symbol(0, 0);
public sealed record PyDedent() : Symbol(0, 0);
public sealed record PyTypeString(int StartPos, int EndPos, string Comment, Trivia[] Trivias) : Symbol(StartPos, EndPos);